
[functions.echo-client-info]
enabled = true
verify_jwt = true
import_map = "./functions/echo-client-info/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/echo-client-info/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/echo-client-info/*.html" ]
